export const TAG_LIST = [
  'Animals',
  'Arrows',
  'Communication',
  'Creative & Design',
  'Education',
  'Emotions',
  'Files & Folders',
  'Finance',
  'Flags',
  'Food & Drink',
  'Hands',
  'Health & Medical',
  'Home',
  'Media',
  'Miscellaneous',
  'Nature',
  'Navigation & Maps',
  'People',
  'Security',
  'Shopping',
  'Smileys',
  'Social',
  'Sports & Fitness',
  'Symbols & Math',
  'Technology',
  'Transport',
  'Travel & Places',
  'UI & Interface',
  'Weather',
  'Work & Office',
]
